version: '3'
services:
  spark:
    # image: apache/spark:3.5.4
    build:
        context: .
        dockerfile: Dockerfile.spark
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080" # Master UI
      - "7077:7077" # Master RPC
      - "4040:4040" # Local Worker UI
    volumes:
      - ./spark/kaggle.json:/root/.kaggle/kaggle.json
      - ./code:/opt/spark/code
      - ./data:/data
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    restart: always

  hive-metastore-db:
    image: postgres:17.2-alpine3.21
    container_name: hive-metastore-db
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d metastore -U hive"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  hive-metastore:
    # image: apache/hive:3.1.3
    build:
      context: .
      dockerfile: Dockerfile.hive-metastore
    container_name: hive-metastore
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-metastore-db:5432/metastore -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive -Ddatanucleus.autoCreateSchema=false
    ports:
      - "9083:9083"
    depends_on:
      hive-metastore-db:
        condition: service_healthy
    restart: always

  hive-server:
    image: apache/hive:3.1.3
    container_name: hive-server
    environment:
      - SERVICE_NAME=hiveserver2
      - SERVICE_OPTS=-Dhive.metastore.uris=thrift://hive-metastore:9083 -Dhive.metastore.schema.verification=false
      - HIVE_SCHEMA_VERIFICATION=false
      - HIVE_SCHEMA_TOOL_VALIDATE=false
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./hive/warehouse:/opt/hive/data/warehouse
    depends_on:
      - hive-metastore
    restart: always