FROM apache/hive:3.1.3

# 최신 PostgreSQL JDBC 드라이버 다운로드 및 설치
USER root
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://jdbc.postgresql.org/download/postgresql-42.7.1.jar -P /opt/hive/lib/ && \
    apt-get remove -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# hive-site.xml에서 JDBC 드라이버 클래스 이름 변경
RUN sed -i 's/org.postgresql.Driver/org.postgresql.Driver/g' /opt/hive/conf/hive-site.xml

USER hive